#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD | grep --quiet 'package-lock.json'; then
  echo "Detected changes in package-lock.json. Running npm install..."
  npm install --no-audit --no-fund
fi
